# Generated by Django 4.1.3 on 2022-12-21 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppManejo_Usuario', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
